version: '3'

services:

  onos:
    image: onosproject/onos:latest
    ports:
     - "8181:8181"
     - "6653:6653"
     - "6633:6633"
    hostname: onos
    container_name: onos

  dp:
    image: letitbeat/dp-emulator:latest
    privileged: true
    tty: true
    pid: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    container_name: dp

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongotest

  mongo-express:
    image: mongo-express
    restart: always
    ports:
        - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongotest

  analyzer:
    image: letitbeat/dp-analyzer:latest
    hostname: analyzer
    ports:
      - "5000:5000"

  web:
    image: letitbeat/dpd-ui:latest
    ports:
      - "8088:80"
    environment:
          - TARGET=http://127.0.0.1:8088
